name: 🚀 Despliegue Automático Las Pilcas

on:
  push:
    branches:
      - main  # <--- ESTO es lo que hace que se active SOLO al hacer push

jobs:
  web-deploy:
    name: 🎉 Subiendo archivos al hosting
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener código desde GitHub
      uses: actions/checkout@v3

    - name: 🟢 Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 🎨 Generar CSS de Tailwind
      run: npx --yes tailwindcss@3 -i tailwind.input.css -o tailwind.min.css --minify

    - name: 📂 Sincronizar vía FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: laspilcas.cl
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        local-dir: ./
        exclude: |
          **/.git*
          **/.github*
          _version_antigua/**